spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:4306/stock_concurrency}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:password1}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
